### ISSUE TITLE
Release 0.5.0 not working / plus button does not create new todos 

### ISSUE THREAD

**Issue by bene64** [powerpaul17/yatoo#3]
**Describe the bug**

A press of the "+" button (top right) only highlights the button. No new todo gets created.

**To Reproduce**

1. Open the app
2. Click on "+"
3. Nothing happens

**Expected behavior**

There should be the possibility to add new todos

**Screenshots**

See here: https://social.anoxinon.de/@kaputt/111522854822810084

**App information (please complete the following information):**

- App version:

0.5.0 (F-Droid)

**Smartphone :**

different ones, for example https://social.anoxinon.de/@kaputt/111522854822810084

**Additional context**

There are already 2 reports on the F-Droid new app announcement on mastodon. I can reproduce this issue too.

**Comment by powerpaul17** [comment]
Hello and thanks for the bug report! This is actually already fixed in 9777ca4483c902963fa7c3610ce46e2952e601bb. But I haven't done another release yet since I found another glitch I wanted to fix first..
