### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [powerpaul17/yatoo#6]
See https://monitor.f-droid.org/builds/log/com.paultirk.yatoo/18#site-footer

In your apk, assets/public/main.js has the commit hash but somehow the apk build by F-Droid has a `void 0` there. I fixed it with sed but maybe you know a proper solution. Thanks!

**Comment by powerpaul17** [comment]
Hello, thanks, I already saw that the build failed and was wondering who changed the metadata :sweat_smile:

Basically I changed the build process to pass the commit hash as environment variable and forgot to update it in the f-droid repo. I'll make a PR there.

**Comment by powerpaul17** [comment]
[https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14956](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14956)

**Comment by linsui** [comment]
Lol. thanks!

**Comment by licaon-kter** [comment]
reopen: https://gitlab.com/fdroid/fdroiddata/-/jobs/8048997546


/LE: diff log: [yat20.log](https://github.com/user-attachments/files/17325610/yat20.log)

**Comment by powerpaul17** [comment]
Thanks, I'll look into it :slightly_smiling_face:

**Comment by powerpaul17** [comment]
I fixed the Release, the commit hash had a length of 8. Can you restart the check or will it be done automatically?

**Comment by licaon-kter** [comment]
Confirmed, thanks
